# Generated by Django 5.1.1 on 2024-10-11 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0004_alter_borrowing_options"),
        ("payment", "0002_alter_payment_borrowing_payment_unique_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="borrowing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="borrowing.borrowing",
            ),
        ),
    ]
