# Generated by Django 5.1.1 on 2024-09-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                (
                    "cover",
                    models.CharField(
                        blank=True,
                        choices=[("HR", "Hard"), ("SF", "Soft")],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("inventory", models.IntegerField(default=1)),
                (
                    "daily_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
            options={
                "ordering": ["title"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("inventory__gt", 0)), name="inventory_gt_0"
                    )
                ],
            },
        ),
    ]
