# Generated by Django 5.1.1 on 2024-09-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="book",
            name="inventory_gt_0",
        ),
        migrations.AddConstraint(
            model_name="book",
            constraint=models.CheckConstraint(
                condition=models.Q(("inventory__gte", 0)), name="inventory_gte_0"
            ),
        ),
    ]
